// Record ids are generated by the client so that a food or entry created offline can be edited,
// reordered, and deleted long before any server has seen it. The format matches PocketBase's own
// id format so the server can store the id verbatim instead of assigning its own.
const ALPHABET = "abcdefghijklmnopqrstuvwxyz0123456789";
const ID_LENGTH = 15;
const UNBIASED_LIMIT = Math.floor(256 / ALPHABET.length) * ALPHABET.length;

export function newId(): string {
  let id = "";
  const bytes = new Uint8Array(ID_LENGTH);
  while (id.length < ID_LENGTH) {
    crypto.getRandomValues(bytes);
    for (let i = 0; i < bytes.length && id.length < ID_LENGTH; i += 1) {
      if (bytes[i] < UNBIASED_LIMIT) id += ALPHABET[bytes[i] % ALPHABET.length];
    }
  }
  return id;
}

// Identifies which device wrote a change. It breaks ties when two devices edit the same record
// within the same millisecond, so it only has to be stable and distinct, never meaningful.
export function newDeviceId(): string {
  return newId();
}

// Merge order compares these as plain strings, so every writer must produce the exact same
// shape. `toISOString` always emits three-digit milliseconds; the server rejects anything else.
export function nowInstant(): string {
  return new Date().toISOString();
}
